name: ML_Library
dependencies:
- python==3.6.5
- numpy
- pandas
- cudatoolkit
- cudnn
- tensorflow-gpu
- pip:
  - watchdog==0.8.2
  - pillow
  - pymongo
  - websockets
  - opencv-python
  - absl-py==0.7.1
  - astor==0.7.1
  - dlib==19.17.0
  - gast==0.2.2
  - grpcio==1.19.0
  - h5py==2.9.0
  - imutils==0.5.2
  - Keras==2.2.4
  - Keras-Applications==1.0.7
  - Keras-Preprocessing==1.0.9
  - Markdown==3.1
  - mock==2.0.0
  - numpy==1.16.2
  - opencv-contrib-python==4.0.0.21
  - pandas==0.24.2
  - pbr==5.1.3
  - pip==19.0.3
  - protobuf==3.7.1
  - python-dateutil==2.8.0
  - pytz==2018.9
  - PyYAML==5.1
  - scikit-learn==0.20.3
  - scipy==1.2.1
  - setuptools==40.8.0
  - six==1.12.0
  - tensorboard
  - tensorflow-estimator
  - termcolor==1.1.0
  - tqdm==4.31.1
  - Werkzeug==0.15.1
  - wheel==0.33.1
